name: connect to server by ssh
on: workflow_dispatch
jobs:
    build:
        name: Build & Publish
        runs-on: ubuntu-latest
        steps:
          - name: "connect to server"
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6ToWIypiEQSqWo9l3QxNQ522awe4JWWaLCiCFO9vove0DZksMsLltIpT7YD1If7nAWxDg07FTxzF3nEL5zv7+hcB5ShRrmMODbZw4lU7dsGV9pdw34NOWRF64X4MXMDFrfGO27f9EFkS5zHPmoudSoLD1qVLidwfsQqP9iMnmccYoIZJMxyTDXc4hTWWc9yUTIGZOo52mB77FVEP9OUDwvUYQxlYwpR+Dl4fmwuEqQhQw3lpgnP4o8dE14Pw+O1ok00P3g68dCv2Ytf9QRmuIYxWM+l4AVLW9ao51Bn4+hkUuerep3JZu3WJlXIZdHhKN38IE6p8gCy/QI4efmidrKWQzYU7C8g3sJQ1McaUWkdAsYiQQd5IX5K1+2eHLjaMVA3QYGLom9jiM9ZX6MzFn6gh3q5kfCV4T/sN4FElYHbzq/Mh6zEhfU5eK7KbQLHX7Ako2mSZOTmGyahOvvDr6Sm0Kge/ARpBazcuH+H54C8aBbxmrezxvd75QIvRrVg0= root@1420539-co69845.tw1.ru
                port: ${{ secrets.SERVER_PORT }}
                script: |
                  echo test
